#include "./Facade.h"

int main() {
    BytecodeStream output;
    Parser parser;

    // Разбираем исходный код
    std::string sourceCode = "if x > 10";
    ProgramNode* programNode = parser.parse(sourceCode);

    // Генерируем код (код не генерируется, берём для пимера заготовку)
    RISCCodeGenerator generator(&output);
    programNode->traverse(&generator);

    // Читаем сгенерированный байт-код
    std::cout << "Generated bytecode: " << output.read() << std::endl;

    delete programNode;

    return 0;
}